openapi: 3.0.1
info:
  description: API for futoVerseny
  title: API
  version: 1.0.0
servers:
- url: https://localhost:8080/v1
paths:
  /getRunners:
    get:
      operationId: GetRunners
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Runners'
          description: List of the runners
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        "404":
          content: {}
          description: Not found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      summary: Returns a list of runners
      x-accepts:
      - application/json
  /addRunner:
    post:
      operationId: AddRunner
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Runner'
        required: true
      responses:
        "200":
          content: {}
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      summary: Add a new runner
      x-codegen-request-body-name: runner
      x-content-type: application/json
      x-accepts:
      - application/json
  /getRaceRunners/{ID}:
    get:
      operationId: GetRaceRunners
      parameters:
      - description: id of the runner
        in: path
        name: ID
        required: true
        schema:
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Runners'
          description: List of the runners from the race
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        "404":
          content: {}
          description: Not found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      summary: Returns a list of runners from the race
      x-accepts:
      - application/json
  /updateRace:
    post:
      operationId: UpdateRace
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Race'
        required: true
      responses:
        "200":
          content: {}
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        "404":
          content: {}
          description: Not found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      summary: Update race name and/or distance
      x-codegen-request-body-name: race
      x-content-type: application/json
      x-accepts:
      - application/json
  /addResult:
    post:
      operationId: AddResult
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Results'
        required: true
      responses:
        "200":
          content: {}
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      summary: Add a new result for the runner and race
      x-codegen-request-body-name: result
      x-content-type: application/json
      x-accepts:
      - application/json
  /getAverageTime/{VERSENYID}:
    get:
      operationId: GetAverageTime
      parameters:
      - description: Id of the race
        in: path
        name: VERSENYID
        required: true
        schema:
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAverageTime_200_response'
          description: Average time of results for the race
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        "404":
          content: {}
          description: Not found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      summary: Returns the average time of result for the given race
      x-accepts:
      - application/json
components:
  schemas:
    ErrorResponse:
      example:
        ErrorMsg: ErrorMsg
      properties:
        ErrorMsg:
          type: string
      type: object
    Runner:
      example:
        sex: male
        name: name
        id: 0
        age: 6
      properties:
        id:
          type: integer
        sex:
          enum:
          - male
          - female
          type: string
        age:
          type: integer
        name:
          type: string
      required:
      - age
      - id
      - name
      - sex
      type: object
    Runners:
      items:
        $ref: '#/components/schemas/Runner'
      type: array
    Race:
      example:
        distance: 0
        name: name
        id: 6
      properties:
        name:
          type: string
        distance:
          description: distance in km
          type: integer
        id:
          type: integer
      required:
      - id
      type: object
    Result:
      example:
        raceId: 6
        runnerId: 0
        time: 1
      properties:
        runnerId:
          type: integer
        raceId:
          type: integer
        time:
          description: time in min
          type: integer
      required:
      - raceId
      - runnerId
      - time
      type: object
    Results:
      items:
        $ref: '#/components/schemas/Result'
      type: array
    GetAverageTime_200_response:
      example:
        averageTime: 0
      properties:
        averageTime:
          description: average time in min
          type: integer
      type: object
x-original-swagger-version: "2.0"
